#pragma once
// from glfw
#define AURORA_MOUSE_BUTTON_1         0
#define AURORA_MOUSE_BUTTON_2         1
#define AURORA_MOUSE_BUTTON_3         2
#define AURORA_MOUSE_BUTTON_4         3
#define AURORA_MOUSE_BUTTON_5         4
#define AURORA_MOUSE_BUTTON_6         5
#define AURORA_MOUSE_BUTTON_7         6
#define AURORA_MOUSE_BUTTON_8         7
#define AURORA_MOUSE_BUTTON_LAST      AURORA_MOUSE_BUTTON_8
#define AURORA_MOUSE_BUTTON_LEFT      AURORA_MOUSE_BUTTON_1
#define AURORA_MOUSE_BUTTON_RIGHT     AURORA_MOUSE_BUTTON_2
#define AURORA_MOUSE_BUTTON_MIDDLE    AURORA_MOUSE_BUTTON_3